-- AlterTable
ALTER TABLE `pedido` ADD COLUMN `hallazgoId` VARCHAR(191) NULL,
    MODIFY `estado` ENUM('PENDIENTE', 'SOLICITADO_POR_CLIENTE', 'DESPACHADO', 'RECHAZADO', 'ENTREGADO', 'CANCELADO') NOT NULL DEFAULT 'PENDIENTE';

-- AddForeignKey
ALTER TABLE `Pedido` ADD CONSTRAINT `Pedido_hallazgoId_fkey` FOREIGN KEY (`hallazgoId`) REFERENCES `Hallazgo`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
