-- AlterTable
ALTER TABLE `pedido` MODIFY `estado` ENUM('PENDIENTE', 'SOLICITADO_POR_KIT', 'SOLICITADO_POR_CLIENTE', 'DESPACHADO', 'RECHAZADO', 'ENTREGADO', 'CANCELADO') NOT NULL DEFAULT 'PENDIENTE';
